---
- name: Install/upgrade motion/motioneye depenencies.
  become: true
  apt:
    name:
      - ffmpeg 
      - libcamera-tools
      - motion
    state: present

- name: adding motion user to gpio group 
  become: true
  user:
    name: motion
    groups: gpio
    append: yes

- name: setup directories
  become: true
  block:
    - name: log directory
      file:
        path: /var/log/motion
        state: directory
        mode: '0755'
        owner: motion

- name: Ensure motion is enabled using libcamerify
  become: true
  lineinfile:
    path: /lib/systemd/system/motion.service
    regexp: '^ExecStart=/usr/bin/motion'
    line: 'ExecStart=/usr/bin/libcamerify motion'
  notify: restart motion

- name: Install motion configuration.
  become: true
  copy:
   src: files/motion/motion.conf
   dest: /etc/motion/motion.conf
  notify: restart motion

- name: Install motion camera configuration.
  become: true
  copy:
   src: files/motion/camera-1.conf
   dest: /etc/motion/camera-1.conf
  notify: restart motion

# - name: Install motioneye.
#   become: true
#   pip:
#     name: https://github.com/motioneye-project/motioneye/archive/dev.tar.gz

# - name: Ensure motioneye config directory present.
#   become: true
#   file:
#     path: /etc/motioneye
#     state: directory
#     mode: '0755'

# - name: Copy config for motioneye. 
#   become: true
#   copy:
#     src: files/motioneye.conf
#     dest: /etc/motioneye/motioneye.conf
#   notify: restart motioneye

# - name: Copy config for motion. 
#   become: true
#   copy:
#     src: files/motion.conf
#     dest: /etc/motioneye/motion.conf
#   notify: restart motioneye

# - name: Copy config for camera 1.
#   become: true
#   copy:
#     src: files/camera-1.conf
#     dest: /etc/motioneye/camera-1.conf
#   notify: restart motioneye

# - name: Ensure motioneye media directory present.
#   become: true
#   file:
#     path: /var/lib/motioneye
#     state: directory
#     mode: '0755'

# - name: Copy service script for motioneye. 
#   become: true
#   copy:
#     src: files/motioneye.service.conf
#     dest: /etc/systemd/system/motioneye.service
#   notify: restart motioneye

# - name: start motioneye service at 6am.
#   become: true
#   cron:
#     name: start motioneye service
#     minute: 0
#     hour: 6
#     user: root
#     job: "service motioneye start > /dev/null"

# - name: stop motioneye service at 21pm.
#   become: true
#   cron:
#     name: stop motioneye service
#     minute: 0
#     hour: 21
#     user: root
#     job: "service motioneye stop > /dev/null"
